development:
  adapter: postgresql
  encoding: unicode
  database: fashion-hackathon-13_development
  pool: 5
  username: strivedi
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: fashion-hackathon-13_test
  pool: 5
  username: strivedi
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: fashion-hackathon-13_production
  pool: 5
  username: strivedi
  password:
